# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }: {
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  fileSystems."/boot/efi" = {
    # device = pkgs.lib.mkOverride 0 "/dev/disk/by-id/nvme-CT1000P5PSSD8_2135313B98F0-part1";
    device = "/dev/disk/by-uuid/F872-FED1";
    fsType = "vfat";
    options = [ "defaults" "noatime" "nodiratime" "discard" ];
  };

  fileSystems."/" = {
    # device = pkgs.lib.mkOverride 0 "/dev/disk/by-id/dm-name-vg-root";
    device = "/dev/disk/by-uuid/4718d5fc-375a-4eb6-8fde-726e245fea0e";
    fsType = "ext4";
    options = [ "defaults" "noatime" "nodiratime" "discard" ];
  };

  fileSystems."/home" = {
    # device = "/dev/disk/by-id/dm-name-vg-home";
    device = "/dev/disk/by-uuid/cb4ee535-0418-4cbb-a65f-25671a4d90a9";
    fsType = "btrfs";
    options = [ "defaults" "noatime" "nodiratime" "discard=async" ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
